title: Design of energy flexibility solutions in the context \n of \n Positive Energy Districtsexibility solutions in the context of Positive Energy Districts 
description: Concerns tasks 3.1 and 3.2 of work package 3 in PERSIST project
show_downloads: false
google_analytics:
theme: null
url: https://brauliobarahona.github.io/PERSIST-SwissData/
plugins:
  - jekyll-seo-tag